name: Nitro
version: ${project.version}
main: thesugarchris.nitro.Nitro
api-version: 1.13
commands:
  balance:
  balancetop:
  ban:
  craft:
  echest:
  eco:
  flyspeed:
  hat:
  hg:
  home:
  homes:
  kick:
  mute:
  nick:
  nuke:
  pay:
  sethome:
  test:
  top:
  tpall:
  unmute:
  withdraw: