name: Nitro
version: ${project.version}
main: thesugarchris.nitro.Nitro
api-version: 1.13
commands:
  balance:
  eco:
  pay:
  nick:
  mute:
  unmute:
  kick:
  ban:
  top:
  hat:
  withdraw:
  sethome:
  home:
  homes:
  tpall:
  hg:
  test: